name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-diff:
    name: Check diff size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Check that diff isn't too large"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FILES_CHANGED=$(gh pr diff ${{github.event.pull_request.number}} --name-only | wc -l)
          echo "Number of files changed in this PR: ${FILES_CHANGED}"
          if [ $FILES_CHANGED -gt 20 ]
          then
            echo "The diff is too large. You've changed ${FILES_CHANGED} in this PR!"
            exit 1
          else
            echo "The diff looks nice and small - good work! ðŸ˜Ž"
            exit 0
          fi
